spring.config.import=optional:file:.env[.properties]
spring.application.name=springboot-backend

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update

api.ratelimit.global.capacity=10
api.ratelimit.global.minutes=1

api.ratelimit.specific.[/api/v1/sources].capacity=5
api.ratelimit.specific.[/api/v1/sources].minutes=1