spring.config.import=optional:file:.env[.properties]
spring.application.name=springboot-backend

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/employee_management_system?allowPublicKeyRetrieval=true&useSSL=false}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:root}

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update